# Generated by Django 4.0.3 on 2022-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leftEye', models.FloatField()),
                ('rightEye', models.FloatField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
